### ISSUE TITLE
Trying to write on docker read only mount point

### ISSUE THREAD

**Issue by verovaleros** [stratosphereips/AIP-Blacklist-Algorithm#5]
Not sure why the aip is trying to write on a docker mounted volume that should be read only (it contains the raw data):

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/data/access.py", line 61, in _process_zeek_file
    getrawdata(date)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/data/functions.py", line 61, in getrawdata
    makedirs(p, exist_ok=True)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/home/aip/AIP/data/raw/2022-11-12'
"""

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aip/AIP/bin/aip", line 73, in <module>
    blocklist = pn.run()
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/models/prioritize.py", line 169, in run
    self.db = Knowledgebase(load_until=for_date - timedelta(days=1))
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/models/prioritize.py", line 110, in __init__
    self._load_knowledge_until(day)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/models/prioritize.py", line 100, in _load_knowledge_until
    self.build(end=datetime.strptime(day, '%Y-%m-%d').date())
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/models/prioritize.py", line 134, in build
    last_knowledge = _add_knowledge(last_knowledge, day)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/models/prioritize.py", line 44, in _add_knowledge
    attacks = get_attacks(dates=[day])
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/data/access.py", line 170, in get_attacks
    extract_attacks(datesnotready)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/data/access.py", line 144, in extract_attacks
    process_zeek_files(datesnotready)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/aip/data/access.py", line 130, in process_zeek_files
    Parallel(n_jobs=12, backend='multiprocessing')(delayed(_process_zeek_file)(date) for date in dates)
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/aip/miniconda3/envs/aip/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
OSError: [Errno 30] Read-only file system: '/home/aip/AIP/data/raw/2022-11-12'
```

**Comment by Aman123lug** [comment]
@verovaleros  AIP docs tutorial is not completed till now then it's very difficult to understand i know what is idea behind this how it's work but not able to stup-up in my local machine.
can you share me some docs about run AIP with docker

**Comment by jwackito** [comment]
Issue solved in produciton. @Aman123lug I'm updating the documentation for development soon. Stay tuned.
